#!/bin/bash
# shell alias
alias so="source"
alias rl="reload_shell"
alias cl="clear"
alias b="popd > /dev/null"
alias mv="mv -i"
alias cpi="cp -i"
alias tL="tree -L"
alias tN="tree -I node_modules"
alias vim.tiny="echo vim.tiny disabled"
alias help="bat ~/.dotfiles/refs/clt.md"
alias isme="source ~/.dotfiles/config/gpg.sh"
alias sD="set_dst"
alias gD="go_dst"
alias mD="mv_to_dst"
alias cpD="cp_to_dst"
alias np="nopassphrase"

# aliases for ls
alias l="eza --icons || ls --color=tty"
alias lsa="eza -lah || ls -lah"
alias la="eza -lAh || ls -lAh"
alias l.="eza -d .* || ls -d .* --color=auto"
alias ll="eza -lh || ls -lh"
alias ll.="eza -lh -d .* || ls -lh -d .*"
alias lt="eza --tree -L"

# edit and/or reload config files
alias usevm="alias vi=\"vim\"; echo using vim; lshu"
alias usenv="alias vi=\"nvim\"; #echo using nvim; lshu"
alias vi="nvim"

alias vrc="vi ~/.vimrc"
alias nvr="vi ~/.dotfiles/config/nvim/init.lua"
alias brc="vi ~/.bashrc"
alias zrc="vi ~/.zshrc"
alias tcf="vi ~/.tmux.conf"
## aliases
alias al="vi ~/.aliases"
alias lal="source ~/.aliases; echo '~/.aliases updated'"
## shell functions
alias shu="vi ~/.shell_utils"
alias lshu="source ~/.shell_utils; echo '~/.shell_utils updated'"
## local environments and aliases
alias lc="vi ~/.localrc"
alias llc="source ~/.localrc; echo '~/.localrc updated'"
alias laa="lal; lshu; llc;"

# dotfiles
export DOTFILES="$HOME/.dotfiles"
alias sysinfo="cat ~/sysinfo"
alias .f="cd $DOTFILES/"
alias bootstrap="source $DOTFILES/bootstrap.sh"
alias .s="cd $DOTFILES/scripts"
alias .c="cd $DOTFILES/config"
alias .r="cd $DOTFILES/refs"
alias nv="nvim"
alias .nvimcheck="readlink -f $HOME/.config/nvim"
alias .nvim="cd $(.nvimcheck); tree"

# service
alias wttr="curl wttr.in"
alias weather="wttr"

# git
alias gs.="gss ."
alias lg="lazygit"
alias glc="git log \
  --oneline --decorate \
  --pretty='%Cred%h%Creset - %Cgreen(%ad) %C(auto)%d%Creset %s %C(bold blue)<%an>%Creset' \
  --date=short"
alias gcmi="gcmsg 'init commit'"

# fzf
alias fzw="fzf \
  --height 40% --layout reverse --info inline --border \
  --preview 'file {}' --preview-window up,1,border-horizontal \
  --color 'fg:#bbccdd,fg+:#ddeeff,bg:#334455,preview-bg:#223344,border:#778899'"

alias fzp="fzf \
  --preview 'bat --style=numbers --color=always --line-range :500 {}'"


# development
alias eslints="npx eslint . --ext .ts,.tsx"
alias eslintjs="npx eslint . --ext .js,.jsx"

# source aliases
source "$HOME/.tmux/aliases.sh"

