# https://hub.docker.com/_/archlinux
FROM archlinux:latest

RUN pacman -Syu --noconfirm \
    git curl vim tmux zsh sudo \
    && pacman -Scc --noconfirm

WORKDIR /root/.dotfiles

COPY . .
RUN ./bootstrap.sh
CMD ["bash"]
