#!/usr/bin/env bash
# Finds a tmux pane running `pomo` and prints its remaining time.
# Used as a #() command in tmux status-right.
# Generated by Claude.ai

pane=$(tmux list-panes -a -F '#{pane_id} #{pane_current_command}' 2>/dev/null \
  | awk '$2 == "pomo" {print $1; exit}')

[ -z "$pane" ] && exit 0

text=$(tmux capture-pane -p -t "$pane" 2>/dev/null)

time=$(echo "$text" | grep -oE '([0-9]{1,2}:)?[0-9]{2}:[0-9]{2}' | tail -n1)

[ -z "$time" ] && exit 0

icon="🍅"
if echo "$text" | grep -q '(paused)'; then
  icon="⏸"
elif echo "$text" | grep -q 'done!'; then
  icon="✅"
fi

echo "$icon $time"
